---
  - set_fact:
      build_dir: /tmp/sb

  - name: create directory for files
    file: path={{ build_dir }}/files state=directory mode=0755

  - name: copy files
    copy: src=files/sample-spring-boot-0.0.1-SNAPSHOT.jar dest={{ build_dir }}/files

  - name: copy more files
    copy: src=Dockerfile dest={{ build_dir }}

  - name: create bootApp
    docker_image: path={{ build_dir }} name="springboot/app" state=present

  - name: start docker bootApp
    docker:
      image: springboot/app
      state: started
      count: 3
      volumes: /tmp
      env:
        SERVICE_80_NAME: http
        SERVICE_NAME: app
        SERVICE_TAGS: production
      ports:
        - "8080"
