---
- name: Install Docker
  yum: pkg=docker-io state=present

- name: Install Docker.py
  pip: name=docker-py state=present version=1.2.3

- name: Start service
  service: name=docker state=started

- name: Install dockerui image
  docker:
    name: dockerui
    image: dockerui/dockerui
    state: started
    volumes: /var/run/docker.sock:/var/run/docker.sock
    ports:
    - "9000:9000"